### ISSUE TITLE
Microsoft.Owin.Host.HttpListener.RequestProcessing.ResponseHeadersDictionary.Set causes an exception for some valid Keep-Alive values

### ISSUE THREAD

**Issue by GCymbala** [aspnet/AspNetKatana#119]
In https://github.com/aspnet/AspNetKatana/blob/dev/src/Microsoft.Owin.Host.HttpListener/RequestProcessing/ResponseHeadersDictionary.cs ...

The `protected override void Set(string header, string value)` method doesn't handle valid Keep-Alive header values like this:

```HTTP
Keep-Alive: timeout=15, max=100
```
Specifically, at lines 101-111, neither if condition is met ...

```c#
            else if (header.Equals(Constants.ConnectionHeader, StringComparison.OrdinalIgnoreCase)
                && value.Equals("close", StringComparison.OrdinalIgnoreCase))
            {
                _response.KeepAlive = false;
            }
            else if (header.Equals(Constants.KeepAliveHeader, StringComparison.OrdinalIgnoreCase)
                && value.Equals("true", StringComparison.OrdinalIgnoreCase))
            {
                // HTTP/1.0 semantics
                _response.KeepAlive = true;
            }
```
Instead, execution falls through to the `else` at line 118:
```c#
            else
            {
                base.Set(header, value);
            }
```

Attempting to set the "Keep-Alive" header this way results in the following  exception:
```
System.ArgumentException: The 'Keep-Alive' header must be modified using the appropriate property or method.
Parameter name: name
   at System.Net.WebHeaderCollection.ThrowOnRestrictedHeader(String headerName)
   at System.Net.WebHeaderCollection.Set(String name, String value)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ResponseHeadersDictionary.Set(String header, String value)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.HeadersDictionaryBase.Set(String key, String[] value)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.HeadersDictionaryBase.set_Item(String key, String[] value)
   at Microsoft.Owin.HeaderDictionary.System.Collections.Generic.IDictionary<System.String,System.String[]>.set_Item(String key, String[] value)
   at System.Web.Http.Owin.HttpMessageHandlerAdapter.SendResponseMessageAsync(HttpRequestMessage request, HttpResponseMessage response, IOwinResponse owinResponse, CancellationToken cancellationToken)
   at System.Web.Http.Owin.HttpMessageHandlerAdapter.<InvokeCore>d__0.MoveNext()
```

**Comment by Tratcher** [comment]
This is a limitation imposed by the underlying System.Net.HttpListener API. There's not a lot we can do about it.

I've never seen a component that used or honored those keep-alive settings. Keep-alive is something of a relic from the HTTP/1.0 days. Do you have a client that will actually honor them?

**Comment by GCymbala** [comment]
Regardless of whether those type of Keep-Alive values are honored, the exception thrown here causes a valid (HTTP 200) `HttpResponseMessage` to become unavailable in my Owin self-hosted WebApi application. (It's essentially acting as a reverse proxy.)
Subsequent requests are OK, because the Keep-Alive response header is not included in the response.
It just seems like throwing an exception in this case throws the baby out with the bath water.

**Comment by Tratcher** [comment]
That exception is out of our control. At best we could filter out the disallowed values, but you could do the same just as easily.
