### ISSUE TITLE
ObjectDisposedException inside Owin...

### ISSUE THREAD

**Issue by ericgu** [aspnet/AspNetKatana#121]
We came across this in one of processes that uses Owin. 

Exception: System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.GetCallCancelled()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.get_CallCancelled()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.PropertiesTryGetValue(String key, Object& value)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.TryGetValue(String key, Object& value)

**Comment by Tratcher** [comment]
This is a race condition that has been addressed for the upcoming 4.0 release.
https://github.com/aspnet/AspNetKatana/issues/108

**Comment by ericgu** [comment]
Thanks a bunch for the quick response...
