### ISSUE TITLE
OwinHttpListenerContext  is disposed too early

### ISSUE THREAD

**Issue by miraer** [aspnet/AspNetKatana#230]
Looks like OwinHttpListenerContext subscribes itself on cancellationToken that is used to notify other layers and in parallel to user’s request handling does
OwinHttpListenerContext.End()
   OwinHttpListenerResponse.End()
      HttpListenerResponse.Close()
         or
      HttpListenerResponse.Abort()

too early, that leads to ObjectDiposedException to be thrown in Web.API stack:

[LogAsync,UnhandledExceptionLogger.cs(20) <NoCorrelationId> ] Exception handling request http://something.com/
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerRequest'.
   at System.Net.HttpListenerRequest.CheckDisposed()
   at System.Net.HttpListenerRequest.get_LocalEndPoint()
   at System.Net.HttpListenerRequest.get_IsLocal()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.GetServerIsLocal()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.get_ServerIsLocal()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.PropertiesTryGetValue(String key, Object& value)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.TryGetValue(String key, Object& value)
   at Microsoft.Owin.OwinContext.Get[T](String key)
   at System.Web.Http.Owin.OwinHttpRequestContext.get_IsLocal()
   at System.Web.Http.Owin.OwinHttpRequestContext.get_IncludeErrorDetail()
   at System.Net.Http.HttpRequestMessageExtensions.CreateErrorResponse(HttpRequestMessage request, HttpStatusCode statusCode, Func`2 errorCreator)
   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Owin.PassiveAuthenticationMessageHandler.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()

**Comment by muratg** [comment]
We won't be fixing this issue. Workaround is simple enough.

**Comment by wangyingmm** [comment]
sorry, but what is the workaround here?

**Comment by Tratcher** [comment]
The client has already disconnected so there's no way for the request to succeed. This becomes a question about how gracefully it fails. Weather you catch this exception or ignore it and let the server catch it, it won't affect the overall application.
