### ISSUE TITLE
Requests hang in PreExecuteRequestHandler pipeline stage in  Microsoft.Owin.Host.SystemWeb

### ISSUE THREAD

**Issue by Peperud** [aspnet/AspNetKatana#291]
OpenIdConnect and WebAPI2 in a large, mostly ASP.NET web forms application.  
What we see is that sometimes a request would get stuck in ```PreExecuteRequestHandler``` pipeline state (and the module would be ```__DynamicModule_Microsoft.Owin.Host.SystemWeb.OwinHttpModule```). It can stay there for a long time. Eventually it is released and an unhandled exception is logged in the event logs (pasted here from the ELK instace)  
```
Exception information: 
    Exception type: HttpException 
    Exception message: The client disconnected.
   at System.Web.Hosting.IIS7WorkerRequest.EndRead(IAsyncResult asyncResult)
   at System.Web.HttpBufferlessInputStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.StreamReader.<ReadToEndAsyncInternal>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.OwinRequest.<ReadFormAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler.<AuthenticateCoreAsync>d__1a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationHandler.<BaseInitializeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```
Can't tell if the client really disconnected or it is _IIS7WorkerRequest_ threating any stream reading error as 'client disconnect'. https://github.com/microsoft/referencesource/blob/aaca53b025f41ab638466b1efe569df314f689ea/System.Web/Hosting/IIS7WorkerRequest.cs#L659

Does not appear to be on cold starts (https://github.com/aspnet/AspNetKatana/issues/51) and it looks like the server is able to serve other requests. 

Memory dump taken while the request is still hanging shows the HttpContext as running, but no thread associated with it.

**Comment by Tratcher** [comment]
This is happening on the `/signin-oidc` request? That's weird, nothing complex would be happening on that code path.

**Comment by Peperud** [comment]
> This is happening on the `/signin-oidc` request? That's weird, nothing complex would be happening on that code path.

No. I see it on WebAPI2 & ASPX requests. The kind that the ```OpenIdConnecAuthenticationtHandler``` should do nothing about.
I'm getting the impression that it hangs here https://github.com/c4net/katanaproject/blob/df66bf44ffc4b5de0ec9a837f4a470614a9c68bf/src/Microsoft.Owin/OwinRequest.cs#L351
I believe, before that, the ```OpenIdConnecAuthenticationtHandler``` has replaced the request.Body stream with a ```MemoryStream``` (to allow rewinding). Haven't heard of any issues with ```ReadToEndAsync``` on a ```MemoryStream```...

**Comment by Tratcher** [comment]
Why is OIDC running on other requests? What did you set CallbackPath and RedirectUri to? OIDC should be used with an exclusive request path such as `/signin-oidc` to avoid interfering with other requests.

**Comment by Peperud** [comment]
Thanks for the response. This is a good question!
It is a big monolithic legacy application. Mostly ASPX web forms, but also ASMX web services, and WebAPI2. It supports its own legacy way of authentication (and SAML) too. The OpenIdConnect authentication is manually triggered from a dedicated aspx page. Basically - if the user wants to login as before - he'll start by going to "LoginLegacy.aspx" and if he wants OIDC - "LoginOIDC.aspx" (which will kick off the challenge) etc. Choices might be simplified on some instances (for some clients) but that's what it is.
```CallbackPath``` is not set. ```RedirectUri``` is getting set on the fly in ```RedirectToIdentityProvider``` along with few other things to support mutlitenancy - ```IssuerAddress```, ```AcrValues``` etc. Right now I'm not sure why we couldn't set the ```CallbackPath``` and still override the ```RedirectUri``` as necessary (it should vary only in query string parameters...I think). I'll look into that.

But otherwise, even if  ```OpenIdConnecAuthenticationtHandler``` is getting more traffic then it should, it shouldn't hang, right?

**Comment by Tratcher** [comment]
? But otherwise, even if OpenIdConnecAuthenticationtHandler is getting more traffic then it should, it shouldn't hang, right?

No, it shouldn't, but making it ignore other requests is likely easier and more beneficial in the long term than trying to debug this specific hang.

**Comment by Peperud** [comment]
Setting the CallbackPath is problematic in the way things are done on our end. 
We have the apps installed on urls like this:
```
https://www.ourhostingsite.com/client1related
https://www.ourhostingsite.com/client2related
...
https://www.ourhostingsite.com/clientNrelated
etc.
```
So I have to set the CallbackPath to ```/client1related/signin-oidc``` etc. In general that's ok, I can put ```client1related``` as a setting in web.config.

...Except that we have cases where on the same IIS server, we host many clients (urls like the above), all pointing to the same set of files on disk. The application resolves the client/tenant based on the incoming url.  

I can't set the callback path to a pattern (something like ```/{whatever}/signin-oidc```), right?

**Comment by Tratcher** [comment]
> I can't set the callback path to a pattern (something like /{whatever}/signin-oidc), right?

Unfortunately not.

You can do a middleware that splices off the client specific prefix (client1related) from Path and puts it in PathBase. 
https://github.com/aspnet/AspNetKatana/blob/0f6dc4bf2722fb08759da3eacaf38f2a098771bd/src/Microsoft.Owin/OwinRequest.cs#L104-L114
The auth middleware only checks Path.
https://github.com/aspnet/AspNetCore/blob/b670246e3de4b7f39b3996e03c48c06e0da05b0b/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L42

**Comment by Peperud** [comment]
> You can do a middleware that splices off the client specific prefix (client1related) from Path and puts it in PathBase.
> https://github.com/aspnet/AspNetKatana/blob/0f6dc4bf2722fb08759da3eacaf38f2a098771bd/src/Microsoft.Owin/OwinRequest.cs#L104-L114
> 
> 
> The auth middleware only checks Path.
> https://github.com/aspnet/AspNetCore/blob/b670246e3de4b7f39b3996e03c48c06e0da05b0b/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L42

Thanks for the suggestion!
There appears to be more to it. The prefix is already in ```PathBase```. However, when the ```CallbackPath``` is set to ```/signin-oidc``` (and the oidc server is posting to ```/client1related/signin-oidc```), it doesn't get handled and ends up with a 404. 

Nonetheless, if in a piece of middleware before the OIDC handler I null ```PathBase```, it seems to work. So this might do.

It's not clear to me what the rules are for ```Path``` and ```PathBase```, what might be changing/using them   etc.

**Comment by Tratcher** [comment]
PathBase is used for scoping, it identifies the root of your site or some sub section of it. Path is relative to PathBase and is what most requests actually check. You want to keep track of both in most cases so that if you need to generate links you have all of the pieces (scheme + host + pathBase + path..). That said, if clearing PathBase works for your scenarios then go ahead.

**Comment by Peperud** [comment]
Thanks. I'll do something like that for the next version.

If you don't mine (and because it is driving me crazy) - presumably the ```StreamReader``` can hang here if the underlying stream is say a ```NetworkStream``` (because the stream might never indicate an end)  https://github.com/aspnet/AspNetKatana/blob/0f6dc4bf2722fb08759da3eacaf38f2a098771bd/src/Microsoft.Owin/OwinRequest.cs#L352 
But ```MemoryStream``` is not like that (...right?).

So is it possible that here https://github.com/aspnet/AspNetKatana/blob/0f6dc4bf2722fb08759da3eacaf38f2a098771bd/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L201-L211
it gets an "endless" stream that actually has ```CanSeek=true``` ?

**Comment by Tratcher** [comment]
> presumably the StreamReader can hang here if the underlying stream is say a NetworkStream (because the stream might never indicate an end)

Only to a point. The server will close the connection if data is not received at a minimal rate.

> it gets an "endless" stream that actually has CanSeek=true ?

"endless"? No. The MemoryStream would never be endless by the time the application received it. It could be large, but not endless.

**Comment by Peperud** [comment]
> > presumably the StreamReader can hang here if the underlying stream is say a NetworkStream (because the stream might never indicate an end)
> 
> Only to a point. The server will close the connection if data is not received at a minimal rate.
> 
Right. And I think that we might be seeing exactly this. 

> > it gets an "endless" stream that actually has CanSeek=true ?
> 
> "endless"? No. The MemoryStream would never be endless by the time the application received it. It could be large, but not endless.

That's my point - if somehow the stream that ends up there is "seekable" (so it is **not** replaced with a ```MemoryStream```), yet fits the above condition to have the ```StreamReader.ReadToEndAsync()``` hang (until the connection is closed).

**Comment by Peperud** [comment]
```
Exception information: 
    Exception type: HttpException 
    Exception message: The client disconnected.
   at System.Web.Hosting.IIS7WorkerRequest.EndRead(IAsyncResult asyncResult)
   at System.Web.HttpBufferlessInputStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.StreamReader.<ReadToEndAsyncInternal>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.OwinRequest.<ReadFormAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler.<AuthenticateCoreAsync>d__1a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```
https://github.com/aspnet/AspNetKatana/blob/0f6dc4bf2722fb08759da3eacaf38f2a098771bd/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L195-L211

I can't quite put it together how the oidc handler, on a `POST` `application/x-www-form-urlencoded` request would end up calling `ReadFormAsync` on an `System.Web.HttpBufferlessInputStream` stream, which is not seek-able?

https://github.com/microsoft/referencesource/blob/aaca53b025f41ab638466b1efe569df314f689ea/System.Web/HttpBufferlessInputStream.cs#L87-L91
