### ISSUE TITLE
System.Net.HttpListenerException when writing to the response stream

### ISSUE THREAD

**Issue by bosh-ms** [aspnet/AspNetKatana#326]
Hello,

Sometimes I get this exception when writing the response to the response body stream.
```
Exception info dump:
System.IO.IOException ---> System.Net.HttpListenerException: The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpResponseStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.<WriteAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.<WriteAsync>d__6.MoveNext()
```

The behaviour is consistent when the client is located in a remote location (e.g., different continent, so assume slower connection) and the response size is a couple of MBs (I was testing on 20MB).
I was not able to repro this behaviour locally, however.

The code looks much like this:
```
Stream originalStream = context.Response.Body;
using (var newBodyStream = new MemoryStream())
{
    context.Response.Body = newBodyStream;

    // Invoking other middlewares
    await this.Next.Invoke(context);

    try
    {
        newBodyStream.CopyTo(originalStream);
    }
    catch (Exception ex)
    {
        // Swallow any exception during sending the response
       ***Getting the exception here***
    }
    finally
    {
        context.Response.Body = originalStream;
    }
}
```

Wireshark shows that the underlying TCP connection stays open (no RST, no FIN), but with no activity. 

Where the issue might be?
Here are some other info that might be useful
1. I'm on OWIN 4.0.0.
1. Does it make sense to update to 4.1.0 to hope the issue will go away? :)
1. Unfortunately it's not an option to "stream" the data directly to the response stream; I have to buffer the data first for other reasons.
1. Since the client does not get any data at all and the connection stays open, how do I actually terminate that connection?

Thanks a lot!

**Comment by Tratcher** [comment]
Aren't you missing a Seek(0, ...) on that newBodyStream before you call CopyTo?

That error implies the request was aborted and/or the server is shutting down. Just how much latency does the client have on their connection? The server enforces a [minimum data rate](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistenertimeoutmanager.minsendbytespersecond?view=netframework-4.8#System_Net_HttpListenerTimeoutManager_MinSendBytesPerSecond) and should terminate the connection if the client does not consume the data fast enough. There are networking tools that allow you to artificially simulate high latency connections that should help you repro locally.

> Unfortunately it's not an option to "stream" the data directly to the response stream; I have to buffer the data first for other reasons.

Such as?

**Comment by bosh-ms** [comment]
In the production code, I have the `Seek()` call before copying the stream, so no issue there :)

I'll try to use those tools to simulate high latency connections and see if that helps to repro locally.

Those reasons are defined by the current business-logic that is hard to change overnight; but we're working on those changes, however. Until then, streaming is not an option :(

**Comment by bosh-ms** [comment]
I'm sorry I never came back to this thread.
The issue was found and resolved; it has nothing to do with OWIN, but has something with Azure instead.
The root cause of the issue was in the configuration of the Azure External IP Address resource: there is a timeout setting for "non-active" connections. After that timeout, IP Address (or Load Balancer associated with it) terminates the connection. However, it does that without sending RST/FIN or any other TCP packet, thus the client is unaware of the fact the connection was actually closed.
Changing that setting to a higher value helped.
