### ISSUE TITLE
Google 3.1.0 Not Working

### ISSUE THREAD

**Issue by JoeDM09** [aspnet/AspNetKatana#39]
I have updated to RC 3.1.0 however seem am still getting issues authenticating.

This is the output from a fiddler:

```
#	Result	Protocol	Host	URL	Body	Caching	Content-Type	Process	Comments	Custom	
9452	200	HTTP	**foo.bar.com**	/Account/Login	7,712	no-cache, no-store; Expires: -1	text/html; charset=utf-8	firefox:17268			
9675	200	HTTP	**foo.bar.com**	/__browserLink/requestData/29b5633f81424b548a2fc4f5842c9006?version=2	3,026	public; Expires: Thu, 30 Mar 2017 05:05:02 GMT	application/json	firefox:17268			
9712	302	HTTP	**foo.bar.com**	/Account/ExternalLogin	0	private		firefox:17268			
9784	302	HTTP	**foo.bar.com**	/signin-google?state=j3HP3orE7tetRGbPwgzhavSX6yfRyWRtFAwQRhgWOlkGuWHrLjbt8-JKWK86dhk0i49vZDC4W5_7dmItoHdMzmJWX_56qYPNNkcJCrV2B7Z0_rYvwP8A92ioWSTlWl-pX7GNxOVnl7PF4g-VAtU9TIlk6l360mGHVFdQYZ34BBvfO-dRKkbIAJ9Fnq1K-8kx4aRreCzW_DhNLEzlvCo-JtiOSHdhMsrZ24OWsuJv5gU&code=4/cZgEy-LQH6WglN3zW5b6xtEhSVYioUxafUNWaGmBz6o&authuser=0&hd=liquidfusion.com.au&session_state=ce8761a407a452f656ccb83df50fca5a403132ae..8cd0&prompt=none	0			firefox:17268			
9785	 - 	HTTP	**foo.bar.com**	/Account/ExternalLoginCallback?error=access_denied	-1			firefox:17268
```

With debugging enabled this is the error:
```
Microsoft.Owin.Security.Google.GoogleOAuth2AuthenticationMiddleware Error: 0 : Authentication failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Owin.Security.Google.GoogleOAuth2AuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
```

I will continue investigating and add any additional information I come across.

**Comment by JoeDM09** [comment]
I believe the issue may be in:
https://github.com/aspnet/AspNetKatana/commit/d12b41c8c7cd6cd1895ccfbfaea8f83619d94ac3

Based on the auto discovery information in https://accounts.google.com/.well-known/openid-configuration 
`internal const string UserInformationEndpoint = "https://www.googleapis.com/plus/v1/people/me"` should point to https://www.googleapis.com/oauth2/v3/userinfo

**Comment by JoeDM09** [comment]
In the end this was not related to this repository. Logging into Google and Enabling the API again seemed to resolve the issue. I'm assuming Google changes something on their end as this resolution was identical for all develop, staging, UAT and production environments.
